get  "/user/goals",                forward:  "/user/showGoals.groovy"
get  "/user/goals/add",            forward:  "/user/addGoal.groovy"
post "/user/goals/insert",         forward:  "/user/insertGoal.groovy"
get  "/user/goals/delete/@id",     forward:  "/user/deleteGoal.groovy?id=@id"
get  "/user/goals/edit/@id",       forward:  "/user/editGoal.groovy?id=@id"
post "/user/goals/update",         forward:  "/user/updateGoal.groovy"